FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm && apk add --no-cache git

RUN mkdir -p backend frontend

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

RUN pnpm install --frozen-lockfile --ignore-scripts

EXPOSE 5173
CMD ["pnpm", "--filter", "starwars-universe-explorer-frontend", "run", "dev", "--", "--host"]