services:
  redis:
    image: redis:alpine
    container_name: starwars-backend-redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis-dev-data:/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: starwars-backend-api-dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SWAPI_BASE_URL=https://swapi.dev/api
      - SWAPI_TIMEOUT=10000
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend/node_modules
    depends_on:
      - redis
    command: pnpm --filter "starwars-universe-explorer-backend" run start:dev
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    container_name: starwars-frontend-dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - app-network
    depends_on:
      - api
    command: pnpm --filter "starwars-universe-explorer-frontend" exec vite --host

volumes:
  redis-dev-data:
    driver: local

networks:
  app-network:
    driver: bridge