FROM node:18-alpine

WORKDIR /app

RUN npm install -g pnpm && apk add --no-cache git

RUN mkdir -p backend frontend

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

RUN pnpm install --frozen-lockfile --ignore-scripts

EXPOSE 3000
CMD ["pnpm", "--filter", "starwars-universe-explorer-backend", "run", "start:dev"]